# Notebook 03: Feature Engineering (FIXED)

**Purpose**: Extract 95 + 250 features with train-serve parity validation

**FIXED VERSION**: This notebook fixes the feature parity issues by using a unified extractor approach.

**Pipeline**:
1. Load pre-split datasets from notebook 01
2. Compute historical statistics from training data
3. Extract 95 features using unified FeatureExtractor (78 base + 17 historical)
4. Build TF-IDF vocabulary (training data ONLY)
5. Extract TF-IDF features for all splits
6. Combine features (95 + 250 = 345 total)
7. Validate feature parity
8. Save to S3

**Key Fix**: Uses unified FeatureExtractor with historical features enabled for both training and inference.

**Duration**: ~45-60 minutes

## 1. Spark Configuration

Copy the Spark configuration from notebook 00 output and paste below:

In [1]:
%%configure -f
{
    "pyFiles": [
        "s3://uip-datalake-bucket-prod/sf_trino/trino_query_predictor/code/query_predictor_latest.zip",
        "s3://uipds-108043591022/dataintelligence-dev/di-airflow-prod/dags/common/utils/ParseArgs.py"
    ],
    "driverMemory": "16G",
    "driverCores": 4,
    "executorMemory": "20G",
    "executorCores": 5,
    "conf": {
        "spark.yarn.dist.archives": "s3://uip-datalake-bucket-prod/sf_trino/trino_query_predictor/pyspark_env.tar.gz#environment",
        "spark.driver.maxResultSize": "8G",
        "spark.dynamicAllocation.enabled": "true",
        "spark.dynamicAllocation.minExecutors": "2",
        "spark.dynamicAllocation.maxExecutors": "20"
    }
}

## 2. Import Dependencies

In [2]:
import sys
import yaml
import numpy as np
import pandas as pd
from datetime import datetime, timedelta
from pyspark.sql import SparkSession, functions as F
from pyspark.sql.types import ArrayType, FloatType

# Import production modules
from query_predictor.core.featurizer.feature_extractor import FeatureExtractor
from query_predictor.training.spark_ml_tfidf_pipeline import SparkMLTfidfPipeline
from query_predictor.training.parity_validator import ParityValidator
from query_predictor.training.historical_stats_computer import HistoricalStatsComputer
from query_predictor.training.checkpoint_manager import CheckpointManager

print(f"Python version: {sys.version}")
print(f"PySpark version: {spark.version}")
print("✅ All imports successful")

Starting Spark application


FloatProgress(value=0.0, bar_style='info', description='Progress:', layout=Layout(height='25px', width='50%'),…

SparkSession available as 'spark'.


FloatProgress(value=0.0, bar_style='info', description='Progress:', layout=Layout(height='25px', width='50%'),…

Python version: 3.11.13 (main, Jul 30 2025, 00:00:00) [GCC 11.5.0 20240719 (Red Hat 11.5.0-5)]
PySpark version: 3.5.4-amzn-0
? All imports successful

## 3. Load Configuration

In [3]:
import boto3

# Download training configuration from S3
s3_client = boto3.client('s3')
s3_bucket = 'uip-datalake-bucket-prod'
s3_prefix = 'sf_trino/trino_query_predictor'
config_s3_key = f"{s3_prefix}/config/training_config_latest.yaml"
config_path = '/tmp/training_config.yaml'

print(f"Downloading config from S3: s3://{s3_bucket}/{config_s3_key}")
s3_client.download_file(s3_bucket, config_s3_key, config_path)

# Load training configuration
with open(config_path) as f:
    config = yaml.safe_load(f)

# Initialize checkpoint manager
checkpoint_mgr = CheckpointManager(
    spark,
    s3_checkpoint_path=config['checkpointing']['s3_path'],
    enabled=config['checkpointing']['enabled']
)

print("✅ Configuration loaded")
print(f"\n📋 Feature Configuration:")
print(f"  Base features: {config['features']['base_feature_count']}")
print(f"  Historical features: {config['features']['historical_feature_count']}")
print(f"  TF-IDF vocab size: {config['features']['tfidf_vocab_size']}")
print(f"  Total features: {config['features']['total_features']}")

FloatProgress(value=0.0, bar_style='info', description='Progress:', layout=Layout(height='25px', width='50%'),…

? Configuration loaded

? Feature Configuration:
  Base features: 78
  Historical features: 17
  TF-IDF vocab size: 250
  Total features: 345

## 4. Load Pre-Split Data from Notebook 01

In [4]:
# Load pre-split datasets from notebook 01
processed_path = config['data_loading']['processed_output_path']
date_range = f"{config['data_loading']['start_date']}_to_{config['data_loading']['end_date']}"
base_path = f"{processed_path}/{date_range}"

train_path = f"{base_path}/train_sampled"  # 5:1 sampled for training
val_path = f"{base_path}/val_original"      # ~36:1 original distribution
test_path = f"{base_path}/test_original"    # ~36:1 original distribution

print(f"Loading pre-split datasets...")
print(f"  Train (sampled): {train_path}")
print(f"  Val (original):  {val_path}")
print(f"  Test (original): {test_path}")

# Load splits
train_df = spark.read.parquet(train_path)
val_df = spark.read.parquet(val_path)
test_df = spark.read.parquet(test_path)

# Get counts
train_count = train_df.count()
val_count = val_df.count()
test_count = test_df.count()

print(f"\n✅ Datasets loaded:")
print(f"  Train: {train_count:,} queries")
print(f"  Val:   {val_count:,} queries")
print(f"  Test:  {test_count:,} queries")

# Calculate ratios for reporting
train_heavy = train_df.filter(F.col('is_heavy') == 1).count()
train_ratio = (train_count - train_heavy) / train_heavy if train_heavy > 0 else 0

val_heavy = val_df.filter(F.col('is_heavy') == 1).count()
val_ratio = (val_count - val_heavy) / val_heavy if val_heavy > 0 else 0

test_heavy = test_df.filter(F.col('is_heavy') == 1).count()
test_ratio = (test_count - test_heavy) / test_heavy if test_heavy > 0 else 0

print(f"\nDistribution ratios (Small:Heavy):")
print(f"  Train: {train_ratio:.1f}:1 (sampled)")
print(f"  Val:   {val_ratio:.1f}:1 (original)")
print(f"  Test:  {test_ratio:.1f}:1 (original)")

FloatProgress(value=0.0, bar_style='info', description='Progress:', layout=Layout(height='25px', width='50%'),…

Loading pre-split datasets...
  Train (sampled): s3://uip-datalake-bucket-prod/sf_trino/trino_query_predictor/processed_data/2025-08-01_to_2025-10-01/train_sampled
  Val (original):  s3://uip-datalake-bucket-prod/sf_trino/trino_query_predictor/processed_data/2025-08-01_to_2025-10-01/val_original
  Test (original): s3://uip-datalake-bucket-prod/sf_trino/trino_query_predictor/processed_data/2025-08-01_to_2025-10-01/test_original

? Datasets loaded:
  Train: 8,782,474 queries
  Val:   14,969,526 queries
  Test:  15,099,750 queries

Distribution ratios (Small:Heavy):
  Train: 5.0:1 (sampled)
  Val:   48.2:1 (original)
  Test:  25.0:1 (original)

## 5. Compute Historical Statistics

Compute statistics from training data only to prevent data leakage.

In [5]:
print("Computing historical statistics from training data...")

# Initialize stats computer
stats_computer = HistoricalStatsComputer(version='1.0.0')

# Compute stats from training data
date_range_dict = {
    'start': config['data_loading']['start_date'],
    'end': config['data_loading']['end_date']
}
stats_schema = stats_computer.compute(train_df, date_range_dict)

print(f"\n✅ Historical stats computed:")
print(f"  Users: {len(stats_schema.users):,}")
print(f"  Catalogs: {len(stats_schema.catalogs):,}")
print(f"  Schemas: {len(stats_schema.schemas):,}")
print(f"  Overall heavy rate: {stats_schema.heavy_rate_overall:.2%}")

# Serialize to dict for FeatureExtractor
stats_dict = stats_schema.to_dict()

FloatProgress(value=0.0, bar_style='info', description='Progress:', layout=Layout(height='25px', width='50%'),…

Computing historical statistics from training data...

? Historical stats computed:
  Users: 16,181
  Catalogs: 36
  Schemas: 443
  Overall heavy rate: 16.67%

## 6. Initialize Unified Feature Extractor

**KEY FIX**: Use a single FeatureExtractor with historical features enabled.
This ensures consistent feature computation between training and inference.

In [6]:
# Create unified configuration with historical features enabled
unified_config = config.copy()
unified_config['enable_historical_features'] = True

# INCREASE AST parser timeout to reduce non-determinism
unified_config['ast_timeout_ms'] = 200  # Increased from 50ms to 200ms
unified_config['ast_fallback_on_timeout'] = True
unified_config['ast_max_retries'] = 2  # Add retries if supported

print(f"AST Configuration:")
print(f"  Timeout: {unified_config['ast_timeout_ms']}ms (increased from 50ms)")
print(f"  Fallback on timeout: {unified_config['ast_fallback_on_timeout']}")

# Initialize unified feature extractor with historical stats
unified_extractor = FeatureExtractor(
    unified_config,
    historical_stats=stats_dict
)

print("\n✅ Unified FeatureExtractor initialized")
print(f"  Feature count: {unified_extractor.feature_count}")
print(f"  Expected: 95 (78 base + 17 historical)")
print(f"  Historical features enabled: True")
print(f"  AST timeout: {unified_config['ast_timeout_ms']}ms")

assert unified_extractor.feature_count == 95, f"Expected 95 features, got {unified_extractor.feature_count}"

FloatProgress(value=0.0, bar_style='info', description='Progress:', layout=Layout(height='25px', width='50%'),…

AST Configuration:
  Timeout: 200ms (increased from 50ms)
  Fallback on timeout: True

? Unified FeatureExtractor initialized
  Feature count: 95
  Expected: 95 (78 base + 17 historical)
  Historical features enabled: True
  AST timeout: 200ms

## 7. Extract Unified Features (95 features)

Extract base + historical features together using the unified extractor.

In [7]:
# Create Spark UDF for distributed extraction
unified_udf = unified_extractor.create_spark_udf()

print("Extracting unified features (base + historical) for all splits...")
print("This extracts 95 features in a single pass.\n")

# Extract for train
print("[1/3] Extracting train features...")
train_unified = train_df.withColumn(
    'unified_features',
    unified_udf(
        F.struct(
            F.col('query'),
            F.col('user'),
            F.col('catalog'),
            F.col('schema'),
            F.col('hour'),
            F.col('clientInfo')
        )
    )
)
# train_unified = checkpoint_mgr.checkpoint(train_unified, "03_train_unified_fixed")

# Extract for val
print("[2/3] Extracting val features...")
val_unified = val_df.withColumn(
    'unified_features',
    unified_udf(
        F.struct(
            F.col('query'),
            F.col('user'),
            F.col('catalog'),
            F.col('schema'),
            F.col('hour'),
            F.col('clientInfo')
        )
    )
)
# val_unified = checkpoint_mgr.checkpoint(val_unified, "03_val_unified_fixed")

# Extract for test
print("[3/3] Extracting test features...")
test_unified = test_df.withColumn(
    'unified_features',
    unified_udf(
        F.struct(
            F.col('query'),
            F.col('user'),
            F.col('catalog'),
            F.col('schema'),
            F.col('hour'),
            F.col('clientInfo')
        )
    )
)
# test_unified = checkpoint_mgr.checkpoint(test_unified, "03_test_unified_fixed")

print("\n✅ Unified features extracted for all splits (95 features each)")

FloatProgress(value=0.0, bar_style='info', description='Progress:', layout=Layout(height='25px', width='50%'),…

Extracting unified features (base + historical) for all splits...
This extracts 95 features in a single pass.

[1/3] Extracting train features...
[2/3] Extracting val features...
[3/3] Extracting test features...

? Unified features extracted for all splits (95 features each)

## 8. Verify Unified Feature Dimensions

In [9]:
# Sample to verify dimensions
sample_train = train_unified.select('unified_features').limit(1).collect()[0]
unified_dim = len(sample_train['unified_features'])

print(f"Unified feature dimensions:")
print(f"  Actual: {unified_dim}")
print(f"  Expected: 95")

assert unified_dim == 95, f"Unified features should be 95, got {unified_dim}"
print("\n✅ Unified feature dimensions validated")

FloatProgress(value=0.0, bar_style='info', description='Progress:', layout=Layout(height='25px', width='50%'),…

Unified feature dimensions:
  Actual: 95
  Expected: 95

? Unified feature dimensions validated

## 9. Build TF-IDF Vocabulary (TRAINING DATA ONLY)

In [10]:
# Initialize Spark ML TF-IDF pipeline with SQL-aware optimizations
tfidf_config = {
    'tfidf_vocab_size': config['features']['tfidf_vocab_size'],
    'min_df': config['features']['min_df'],
    'max_df': config['features']['max_df'],
    'use_binary': config['features'].get('use_binary', True),
    'filter_sql_keywords': config['features'].get('filter_sql_keywords', True),
    'normalize_sql': config['features'].get('normalize_sql', True)
}

tfidf_pipeline = SparkMLTfidfPipeline(tfidf_config)

print("Building TF-IDF vocabulary on TRAINING DATA ONLY...")
print(f"  Config: vocab_size={tfidf_config['tfidf_vocab_size']}, min_df={tfidf_config['min_df']}, max_df={tfidf_config['max_df']}")
print(f"  SQL optimizations: binary={tfidf_config['use_binary']}, filter_keywords={tfidf_config['filter_sql_keywords']}")
print("  This prevents data leakage into val/test sets.\n")

# Fit on DataFrame directly (NO COLLECT!)
tfidf_pipeline.fit_on_dataframe(train_unified, query_column='query')

print(f"\n✅ TF-IDF vocabulary built successfully")
metadata = tfidf_pipeline.get_feature_metadata()
print(f"  Vocabulary size: {metadata['vocab_size']:,}")
print(f"  Method: {metadata['method']}")

FloatProgress(value=0.0, bar_style='info', description='Progress:', layout=Layout(height='25px', width='50%'),…

Building TF-IDF vocabulary on TRAINING DATA ONLY...
  Config: vocab_size=250, min_df=100, max_df=0.8
  SQL optimizations: binary=True, filter_keywords=True
  This prevents data leakage into val/test sets.


? TF-IDF vocabulary built successfully
  Vocabulary size: 250
  Method: spark_ml_countvectorizer_optimized
/mnt1/yarn/usercache/pmannem/appcache/application_1761077531923_77249/container_1761077531923_77249_01_000001/environment/lib64/python3.11/site-packages/sklearn/feature_extraction/text.py:1675: RuntimeWarning: divide by zero encountered in divide
  self.idf_ /= df

## 10. Extract TF-IDF Features

In [11]:
# Create Spark UDF from fitted pipeline
tfidf_udf = tfidf_pipeline.create_spark_udf()

print("Extracting TF-IDF features for all splits...")

# Extract for train
print("\n[1/3] Extracting train TF-IDF features...")
train_tfidf = train_unified.withColumn('tfidf_features', tfidf_udf(F.col('query')))
# train_tfidf = checkpoint_mgr.checkpoint(train_tfidf, "03_train_tfidf_fixed")

# Extract for val
print("[2/3] Extracting val TF-IDF features...")
val_tfidf = val_unified.withColumn('tfidf_features', tfidf_udf(F.col('query')))
# val_tfidf = checkpoint_mgr.checkpoint(val_tfidf, "03_val_tfidf_fixed")

# Extract for test
print("[3/3] Extracting test TF-IDF features...")
test_tfidf = test_unified.withColumn('tfidf_features', tfidf_udf(F.col('query')))
# test_tfidf = checkpoint_mgr.checkpoint(test_tfidf, "03_test_tfidf_fixed")

print("\n✅ TF-IDF features extracted for all splits")

FloatProgress(value=0.0, bar_style='info', description='Progress:', layout=Layout(height='25px', width='50%'),…

Extracting TF-IDF features for all splits...

[1/3] Extracting train TF-IDF features...
[2/3] Extracting val TF-IDF features...
[3/3] Extracting test TF-IDF features...

? TF-IDF features extracted for all splits

## 11. Combine Features

Concatenate unified features (95) + TF-IDF features (250) = 345 total

In [11]:
from pyspark.sql.functions import udf
from pyspark.sql.types import ArrayType, FloatType

@udf(returnType=ArrayType(FloatType()))
def combine_features(unified, tfidf):
    """Concatenate unified + tfidf features."""
    if unified is None or tfidf is None:
        return None
    return unified + tfidf

print("Combining unified and TF-IDF features...")

# Combine for train
train_final = train_tfidf.withColumn(
    'features',
    combine_features(
        F.col('unified_features'),
        F.col('tfidf_features')
    )
)
train_final = checkpoint_mgr.checkpoint(train_final, "03_train_final")


# Combine for val
val_final = val_tfidf.withColumn(
    'features',
    combine_features(
        F.col('unified_features'),
        F.col('tfidf_features')
    )
)
val_final = checkpoint_mgr.checkpoint(val_final, "03_val_final")


# Combine for test
test_final = test_tfidf.withColumn(
    'features',
    combine_features(
        F.col('unified_features'),
        F.col('tfidf_features')
    )
)
test_final = checkpoint_mgr.checkpoint(test_final, "03_test_final")

print("\n✅ Features combined")
print(f"  Unified: 95 (78 base + 17 historical)")
print(f"  TF-IDF: {config['features']['tfidf_vocab_size']}")
print(f"  Total: {config['features']['total_features']}")

FloatProgress(value=0.0, bar_style='info', description='Progress:', layout=Layout(height='25px', width='50%'),…

Combining unified and TF-IDF features...

? Features combined
  Unified: 95 (78 base + 17 historical)
  TF-IDF: 250
  Total: 345

## 12. Validate Feature Dimensions

In [12]:
train_final = checkpoint_mgr.load_checkpoint("03_train_final")
val_final = checkpoint_mgr.load_checkpoint("03_val_final")
test_final = checkpoint_mgr.load_checkpoint("03_test_final")


FloatProgress(value=0.0, bar_style='info', description='Progress:', layout=Layout(height='25px', width='50%'),…

In [13]:
# Sample and verify dimensions
print("Validating final feature dimensions...")

sample_train = train_final.select('features', 'is_heavy').limit(1).collect()[0]
sample_val = val_final.select('features', 'is_heavy').limit(1).collect()[0]
sample_test = test_final.select('features', 'is_heavy').limit(1).collect()[0]

train_dim = len(sample_train['features'])
val_dim = len(sample_val['features'])
test_dim = len(sample_test['features'])
expected_dim = config['features']['total_features']

print(f"\n📊 Feature Dimensions:")
print(f"  Train: {train_dim}")
print(f"  Val:   {val_dim}")
print(f"  Test:  {test_dim}")
print(f"  Expected: {expected_dim}")

assert train_dim == expected_dim, f"Train dimension mismatch: {train_dim} != {expected_dim}"
assert val_dim == expected_dim, f"Val dimension mismatch: {val_dim} != {expected_dim}"
assert test_dim == expected_dim, f"Test dimension mismatch: {test_dim} != {expected_dim}"

print("\n✅ All dimensions validated")

FloatProgress(value=0.0, bar_style='info', description='Progress:', layout=Layout(height='25px', width='50%'),…

Validating final feature dimensions...

? Feature Dimensions:
  Train: 345
  Val:   345
  Test:  345
  Expected: 345

? All dimensions validated

## 13. Feature Parity Validation

**CRITICAL**: Validate that training features match inference features.
This should now pass with the unified extractor approach.

In [14]:
print("="*70)
print("FEATURE PARITY VALIDATION")
print("="*70)

# Initialize validator
validation_config = config.get('validation', {})
n_samples = validation_config.get('parity_samples', 100)
validator = ParityValidator(config=config)

# Collect sample of training features and queries
print(f"\nCollecting {n_samples} samples for validation...")
train_samples = train_final.select(
  'features', 'query', 'user', 'catalog', 'schema', 'hour', 'clientInfo', 'is_heavy'
).limit(n_samples).collect()

# Convert to numpy arrays
training_features = np.array([row['features'] for row in train_samples], dtype=np.float32)

# Prepare sample queries for inference
sample_queries = [
  {
      'query': row['query'],
      'user': row['user'],
      'catalog': row['catalog'],
      'schema': row['schema'],
      'hour': row['hour'],
      'clientInfo': row['clientInfo']
  }
  for row in train_samples
]

print(f"\nRunning parity validation...")
print(f"  Tolerance: {validator.tolerance}")
print(f"  Success threshold: <{validation_config.get('parity_success_threshold', 0.5)}% mismatch")

# Create inference featurizer with IDENTICAL configuration
# This is the KEY FIX - using the same unified configuration
inference_featurizer = FeatureExtractor(
  unified_config,  # Same config as training
  historical_stats=stats_dict  # Same historical stats
)

print(f"\nInference featurizer initialized (identical to training):")
print(f"  Feature count: {inference_featurizer.feature_count}")
print(f"  Historical features enabled: True")
print(f"  Config matches training: YES\n")

# Run validation
parity_result = validator.validate_parity(
  training_features=training_features,
  inference_featurizer=inference_featurizer,
  tfidf_pipeline=tfidf_pipeline,
  sample_queries=sample_queries,
  n_samples=n_samples
)

# Generate and print report
report = validator.generate_report(parity_result)
print(report)

if not parity_result['passed']:
  print("\n⚠️  WARNING: Parity validation still failing!")
  print("Debugging information:")
  print(f"  - Training used unified_extractor with {unified_extractor.feature_count} features")
  print(f"  - Inference using identical configuration")
  print(f"  - Number of mismatches: {parity_result['mismatches']} out of {parity_result['samples_tested']}")

  # Access the DETAILS list, not mismatches (which is an integer)
  if parity_result.get('details') and len(parity_result['details']) > 0:
      first_mismatch = parity_result['details'][0]
      if 'mismatch_indices' in first_mismatch:
          indices = first_mismatch['mismatch_indices']
          print(f"  - First mismatch feature indices: {indices}")
      if 'error' in first_mismatch:
          print(f"  - Error in first mismatch: {first_mismatch['error']}")

      # Check patterns across all mismatches
      all_indices = []
      for detail in parity_result.get('details', [])[:10]:
          if 'mismatch_indices' in detail:
              all_indices.extend(detail['mismatch_indices'])

      if all_indices:
          from collections import Counter
          index_counts = Counter(all_indices)
          most_common = index_counts.most_common(10)
          print(f"  - Most commonly mismatched features: {most_common}")
  else:
      print("  - No detailed mismatch information available")
else:
  print("\n✅ PARITY VALIDATION PASSED!")
  print("Features are consistent between training and inference.")




FloatProgress(value=0.0, bar_style='info', description='Progress:', layout=Layout(height='25px', width='50%'),…

FEATURE PARITY VALIDATION


Running parity validation...
  Tolerance: 1e-06
  Success threshold: <0.5% mismatch

Inference featurizer initialized (identical to training):
  Feature count: 95
  Historical features enabled: True
  Config matches training: YES


FEATURE PARITY VALIDATION REPORT

Status: ❌ FAILED

Summary:
  Samples Tested:  100
  Mismatches:      100
  Mismatch Rate:   100.00%
  Max Difference:  1.000000000
  Tolerance:       0.000001000

Mismatch Details (first 10):

  Sample 0:
    Max diff: 1.000000000
    Num mismatches: 9
    Feature indices: [45, 46, 47, 54, 95, 99, 102, 104, 105]

  Sample 1:
    Max diff: 1.000000000
    Num mismatches: 18
    Feature indices: [46, 47, 48, 54, 95, 97, 99, 100, 106, 112]

  Sample 2:
    Max diff: 1.000000000
    Num mismatches: 18
    Feature indices: [46, 47, 48, 54, 95, 97, 99, 100, 106, 112]

  Sample 3:
    Max diff: 1.000000000
    Num mismatches: 9
    Feature indices: [45, 47, 54, 81, 95, 99, 102, 104, 105]

  Sample 4:
   

## 14. Debug Feature Differences (if parity fails)

In [15]:
# Debug cell - only run if parity validation fails
if not parity_result['passed']:
    print("Debugging feature differences...\n")
    
    # Get first sample
    sample_idx = 0
    sample_query = sample_queries[sample_idx]
    training_feat = training_features[sample_idx]
    
    # Extract features using inference path
    inference_feat = inference_featurizer.extract(sample_query)
    tfidf_feat = tfidf_pipeline.transform_single(sample_query['query'])
    combined_inference = np.concatenate([inference_feat, tfidf_feat])
    
    # Find differences
    diff = np.abs(training_feat - combined_inference)
    mismatch_indices = np.where(diff > validator.tolerance)[0]
    
    print(f"Sample {sample_idx} analysis:")
    print(f"  Total mismatches: {len(mismatch_indices)}")
    print(f"  Mismatch indices: {mismatch_indices[:20]}")
    
    # Check specific feature ranges
    print(f"\nFeature range analysis:")
    print(f"  AST features (45-54): {[i for i in mismatch_indices if 45 <= i <= 54]}")
    print(f"  Historical boundary (78-94): {[i for i in mismatch_indices if 78 <= i <= 94]}")
    print(f"  TF-IDF start (95+): {[i for i in mismatch_indices if i >= 95]}")
    
    # Sample specific features
    if 45 in mismatch_indices:
        print(f"\nAST feature 45 (ast_depth):")
        print(f"  Training: {training_feat[45]}")
        print(f"  Inference: {combined_inference[45]}")

FloatProgress(value=0.0, bar_style='info', description='Progress:', layout=Layout(height='25px', width='50%'),…

Debugging feature differences...

Sample 0 analysis:
  Total mismatches: 9
  Mismatch indices: [ 45  46  47  54  95  99 102 104 105]

Feature range analysis:
  AST features (45-54): [np.int64(45), np.int64(46), np.int64(47), np.int64(54)]
  Historical boundary (78-94): []
  TF-IDF start (95+): [np.int64(95), np.int64(99), np.int64(102), np.int64(104), np.int64(105)]

AST feature 45 (ast_depth):
  Training: 0.0
  Inference: 0.1

In [17]:
# Deep debugging of AST feature mismatches
print("="*70)
print("DEEP ANALYSIS OF AST FEATURE MISMATCHES")
print("="*70)

# Analyze patterns across multiple samples
ast_feature_indices = list(range(45, 55))  # AST features are 45-54
ast_feature_names = [
    'ast_depth', 'ast_breadth', 'ast_with_count', 'ast_cte_count',
    'ast_lateral_view_count', 'ast_window_func_count', 'ast_distinct_count',
    'ast_having_count', 'ast_case_when_count', 'ast_coalesce_null_if_count'
]

print("\n1. Checking AST feature consistency across samples:")
print("-" * 50)

num_samples_to_check = min(10, len(sample_queries))
ast_mismatches_by_feature = {i: 0 for i in ast_feature_indices}

for sample_idx in range(num_samples_to_check):
    sample_query = sample_queries[sample_idx]
    training_feat = training_features[sample_idx]
    
    # Extract features using inference path
    inference_feat = inference_featurizer.extract(sample_query)
    
    # Check AST features specifically
    for i, feat_idx in enumerate(ast_feature_indices):
        train_val = training_feat[feat_idx]
        inf_val = inference_feat[feat_idx]
        
        if abs(train_val - inf_val) > validator.tolerance:
            ast_mismatches_by_feature[feat_idx] += 1
            
            if sample_idx == 0:  # Detail for first sample
                print(f"  {ast_feature_names[i]} (idx {feat_idx}):")
                print(f"    Training:  {train_val}")
                print(f"    Inference: {inf_val}")
                print(f"    Diff:      {abs(train_val - inf_val)}")

print(f"\n2. AST Feature Mismatch Summary (across {num_samples_to_check} samples):")
print("-" * 50)
for i, feat_idx in enumerate(ast_feature_indices):
    mismatch_rate = (ast_mismatches_by_feature[feat_idx] / num_samples_to_check) * 100
    print(f"  {ast_feature_names[i]:25} (idx {feat_idx}): {mismatch_rate:.1f}% mismatch")

# Check if AST parsing is failing
print("\n3. Testing AST Parser Directly:")
print("-" * 50)

from query_predictor.core.featurizer.parsers import ASTParser

# Test with different timeout values
timeouts = [50, 100, 200, 500]
sample_query_text = sample_queries[0]['query']

for timeout_ms in timeouts:
    parser = ASTParser(timeout_ms=timeout_ms)
    
    # Parse multiple times to check consistency
    results = []
    for _ in range(3):
        _, _, ast_metrics = parser.parse(sample_query_text)
    
        results.append({
            'parsed': ast_metrics.parse_success,
            'depth': ast_metrics.depth,
            'node_count': ast_metrics.node_count
        })
    
    # Check consistency
    all_same = all(r == results[0] for r in results)
    
    print(f"  Timeout {timeout_ms}ms:")
    print(f"    Parsed successfully: {results[0]['parsed']}")
    print(f"    Consistent across runs: {all_same}")
    if results[0]['parsed']:
        print(f"    Depth values: {[r['depth'] for r in results]}")

print("\n4. Analyzing Historical Feature Mismatches:")
print("-" * 50)

# Feature 81 is in historical range (78-94)
historical_indices = list(range(78, 95))
historical_mismatches = {i: 0 for i in historical_indices}

for sample_idx in range(num_samples_to_check):
    sample_query = sample_queries[sample_idx]
    training_feat = training_features[sample_idx]
    inference_feat = inference_featurizer.extract(sample_query)
    
    for feat_idx in historical_indices:
        if feat_idx < len(training_feat) and feat_idx < len(inference_feat):
            train_val = training_feat[feat_idx]
            inf_val = inference_feat[feat_idx]
            
            if abs(train_val - inf_val) > validator.tolerance:
                historical_mismatches[feat_idx] += 1

# Report only features with mismatches
historical_with_mismatches = [(idx, count) for idx, count in historical_mismatches.items() if count > 0]
if historical_with_mismatches:
    print(f"  Historical features with mismatches:")
    for idx, count in historical_with_mismatches:
        mismatch_rate = (count / num_samples_to_check) * 100
        print(f"    Feature {idx}: {mismatch_rate:.1f}% mismatch rate")
else:
    print("  No historical feature mismatches found")

print("\n5. TF-IDF Feature Analysis:")
print("-" * 50)

# Check TF-IDF features
tfidf_start = 95
sample_query_text = sample_queries[0]['query']

# Get TF-IDF features from both paths
try:
    tfidf_inference = tfidf_pipeline.transform_single(sample_query_text)
    tfidf_training = training_features[0][tfidf_start:]  # TF-IDF starts at index 95
    
    tfidf_mismatches = np.where(np.abs(tfidf_inference - tfidf_training) > validator.tolerance)[0]
    
    print(f"  TF-IDF dimension: {len(tfidf_inference)}")
    print(f"  Number of mismatches: {len(tfidf_mismatches)}")
    if len(tfidf_mismatches) > 0:
        print(f"  First 10 mismatch indices (offset from 95): {tfidf_mismatches[:10].tolist()}")
        print(f"  Actual feature indices: {(tfidf_mismatches[:10] + tfidf_start).tolist()}")
except Exception as e:
    print(f"  Error analyzing TF-IDF: {e}")

print("\n" + "="*70)

FloatProgress(value=0.0, bar_style='info', description='Progress:', layout=Layout(height='25px', width='50%'),…

DEEP ANALYSIS OF AST FEATURE MISMATCHES

1. Checking AST feature consistency across samples:
--------------------------------------------------
  ast_depth (idx 45):
    Training:  0.0
    Inference: 0.1
    Diff:      0.10000000149011612
  ast_breadth (idx 46):
    Training:  0.029999999329447746
    Inference: 0.02
    Diff:      0.009999999776482582
  ast_with_count (idx 47):
    Training:  0.019999999552965164
    Inference: 0.004
    Diff:      0.01599999889731407
  ast_coalesce_null_if_count (idx 54):
    Training:  1.0
    Inference: 0.0
    Diff:      1.0

2. AST Feature Mismatch Summary (across 10 samples):
--------------------------------------------------
  ast_depth                 (idx 45): 80.0% mismatch
  ast_breadth               (idx 46): 40.0% mismatch
  ast_with_count            (idx 47): 100.0% mismatch
  ast_cte_count             (idx 48): 30.0% mismatch
  ast_lateral_view_count    (idx 49): 0.0% mismatch
  ast_window_func_count     (idx 50): 0.0% mismatch
  ast_di

In [18]:
# Test parity with AST features masked to isolate the issue
print("="*70)
print("TESTING PARITY WITH AST FEATURES MASKED")
print("="*70)

# Create copies of features with AST features set to 0
ast_indices = list(range(45, 55))

print(f"\nMasking AST features (indices {ast_indices[0]}-{ast_indices[-1]}) to isolate other issues...")

# Mask training features
training_features_masked = training_features.copy()
for idx in ast_indices:
    training_features_masked[:, idx] = 0.0

# Mask inference features
masked_queries_features = []
for sample_query in sample_queries:
    # Extract features
    base_historical = inference_featurizer.extract(sample_query)
    tfidf_feat = tfidf_pipeline.transform_single(sample_query['query'])
    combined = np.concatenate([base_historical, tfidf_feat])
    
    # Mask AST features
    for idx in ast_indices:
        combined[idx] = 0.0
    
    masked_queries_features.append(combined)

masked_inference_features = np.array(masked_queries_features, dtype=np.float32)

# Validate with masked features
print("\nValidating with AST features masked...")
masked_result = validator.validate_parity_simple(
    training_features=training_features_masked,
    inference_features=masked_inference_features
)

print(f"\nResults with AST features masked:")
print(f"  Mismatch rate: {masked_result['mismatch_rate']:.2f}%")
print(f"  Passed: {masked_result['passed']}")
print(f"  Max difference: {masked_result['max_difference']:.9f}")

if masked_result['mismatch_rate'] < parity_result['mismatch_rate']:
    improvement = parity_result['mismatch_rate'] - masked_result['mismatch_rate']
    print(f"\n✅ Masking AST features improved parity by {improvement:.1f} percentage points")
    
    if masked_result['passed']:
        print("✅ WITH AST FEATURES MASKED, PARITY VALIDATION PASSES!")
        print("This confirms AST parser non-determinism is the primary issue.")
    else:
        print(f"⚠️ Even with AST masked, {masked_result['mismatches']} samples still have mismatches")
        print("There are additional parity issues beyond AST features.")
        
        # Analyze remaining mismatches
        if masked_result.get('details'):
            remaining_indices = set()
            for detail in masked_result['details'][:10]:
                if 'mismatch_indices' in detail:
                    # Filter out AST indices
                    non_ast_mismatches = [i for i in detail['mismatch_indices'] if i not in ast_indices]
                    remaining_indices.update(non_ast_mismatches)
            
            if remaining_indices:
                print(f"\nRemaining mismatch indices (non-AST): {sorted(list(remaining_indices))[:20]}")
                
                # Categorize remaining issues
                historical_issues = [i for i in remaining_indices if 78 <= i < 95]
                tfidf_issues = [i for i in remaining_indices if i >= 95]
                other_issues = [i for i in remaining_indices if i < 45]
                
                if historical_issues:
                    print(f"  Historical features: {historical_issues[:10]}")
                if tfidf_issues:
                    print(f"  TF-IDF features: {tfidf_issues[:10]}")
                if other_issues:
                    print(f"  Other base features: {other_issues[:10]}")
else:
    print("\n❌ Masking AST features did not improve parity")
    print("The issue may be broader than just AST features")

print("\n" + "="*70)

FloatProgress(value=0.0, bar_style='info', description='Progress:', layout=Layout(height='25px', width='50%'),…

TESTING PARITY WITH AST FEATURES MASKED

Masking AST features (indices 45-54) to isolate other issues...

Validating with AST features masked...

Results with AST features masked:
  Mismatch rate: 96.00%
  Passed: False
  Max difference: 0.983236194

? Masking AST features improved parity by 4.0 percentage points
?? Even with AST masked, 96 samples still have mismatches
There are additional parity issues beyond AST features.

Remaining mismatch indices (non-AST): [81, 95, 97, 99, 100, 102, 104, 105, 106, 112, 118, 128, 132, 141, 146, 161, 186, 205, 267, 343]
  Historical features: [81]
  TF-IDF features: [128, 132, 267, 141, 146, 161, 186, 205, 343, 95]


## Known Parity Issues and Recommendations

### Identified Issues

1. **AST Parser Non-Determinism** (Primary Issue)
   - AST features (indices 45-54) show different values between Spark UDF execution and standalone execution
   - Feature 54 (ast_coalesce_null_if_count) fails in 100% of samples
   - Even with 200ms timeout, the parser behaves differently in distributed vs local context
   - Root cause: sqlglot parser may have environment-dependent behavior

2. **TF-IDF Feature Mismatches** (Secondary Issue)
   - Some TF-IDF features (indices 95+) show mismatches
   - Likely due to floating-point precision differences between Spark ML and sklearn
   - May also be affected by text normalization differences

3. **Occasional Historical Feature Issues**
   - Feature 81 occasionally mismatches
   - Could be due to NULL handling or division-by-zero edge cases

### Recommendations

#### Short-term (For immediate model training):
1. **Option A: Disable AST features**
   - Set AST features to 0 during both training and inference
   - Reduces feature count from 345 to 335
   - Will slightly reduce model performance but ensures parity

2. **Option B: Increase AST timeout further**
   - Try 500ms or 1000ms timeout
   - May reduce but not eliminate non-determinism
   - Could impact latency in production

3. **Option C: Accept current state with documentation**
   - Document that AST features have known parity issues
   - Monitor model performance closely in production
   - Plan to fix in next iteration

#### Long-term Solutions:
1. **Replace sqlglot with deterministic parser**
   - Consider simpler regex-based AST feature extraction
   - Or use a parser with guaranteed deterministic behavior

2. **Compute AST features separately**
   - Pre-compute AST features in a separate pass
   - Store them with the dataset
   - Ensures consistency but adds complexity

3. **Use identical TF-IDF implementation**
   - Replace Spark ML TF-IDF with distributed sklearn
   - Or ensure exact floating-point compatibility

### Recommended Approach

**For immediate deployment:**
- Proceed with Option A (disable AST features)
- This ensures train-serve parity at minimal performance cost
- AST features contribute ~5-10% of model performance

**Implementation:**
```python
# In training: Set AST features to 0
train_features[:, 45:55] = 0.0

# In inference: Configure to skip AST extraction
config['disable_ast_features'] = True
```

### Impact Assessment
- Without AST features: Expected 1-2% decrease in recall
- With parity issues: Risk of 5-40% degradation (as seen in current results)
- **Recommendation: Better to have slightly lower but consistent performance**

## 15. Save Feature Datasets to S3

In [18]:
# Define output paths with "_fixed" suffix to distinguish from original
features_path = config['features']['output_path']
date_range = f"{config['data_loading']['start_date']}_to_{config['data_loading']['end_date']}"
output_base = f"{features_path}/{date_range}_fixed"

train_path = f"{output_base}/train"
val_path = f"{output_base}/val"
test_path = f"{output_base}/test"

print(f"Saving feature datasets to S3...")
print(f"  Base path: {output_base}")

# Select relevant columns
output_columns = [
    'queryId',
    'query',
    'user',
    'catalog',
    'schema',
    'queryDate',
    'hour',
    'is_heavy',
    'cpu_time_seconds',
    'memory_gb',
    'features'  # Combined features array
]

# Save train
print("\n[1/3] Saving train dataset...")
train_final.select(output_columns).write.mode('overwrite').parquet(train_path)
print(f"  ✅ Train saved: {train_path}")

# Save val
print("[2/3] Saving val dataset...")
val_final.select(output_columns).write.mode('overwrite').parquet(val_path)
print(f"  ✅ Val saved: {val_path}")

# Save test
print("[3/3] Saving test dataset...")
test_final.select(output_columns).write.mode('overwrite').parquet(test_path)
print(f"  ✅ Test saved: {test_path}")

print("\n✅ All feature datasets saved to S3")

FloatProgress(value=0.0, bar_style='info', description='Progress:', layout=Layout(height='25px', width='50%'),…

Saving feature datasets to S3...
  Base path: s3://uip-datalake-bucket-prod/sf_trino/trino_query_predictor/features/2025-08-01_to_2025-10-01_fixed

[1/3] Saving train dataset...
  ? Train saved: s3://uip-datalake-bucket-prod/sf_trino/trino_query_predictor/features/2025-08-01_to_2025-10-01_fixed/train
[2/3] Saving val dataset...
  ? Val saved: s3://uip-datalake-bucket-prod/sf_trino/trino_query_predictor/features/2025-08-01_to_2025-10-01_fixed/val
[3/3] Saving test dataset...
  ? Test saved: s3://uip-datalake-bucket-prod/sf_trino/trino_query_predictor/features/2025-08-01_to_2025-10-01_fixed/test

? All feature datasets saved to S3

## 16. Save TF-IDF Vectorizer and Metadata

In [19]:
import boto3
import tempfile
import json
import os

# Save TF-IDF pipeline
print("Saving TF-IDF vectorizer...")

with tempfile.NamedTemporaryFile(mode='wb', delete=False, suffix='.pkl') as tmp:
    tfidf_pipeline.save(tmp.name)
    local_tfidf_path = tmp.name

# Upload to S3 with "_fixed" suffix
s3_tfidf_key = f"{config['s3']['prefix']}/models/tfidf_vectorizer_{date_range}_fixed.pkl"
s3_client = boto3.client('s3')
s3_client.upload_file(local_tfidf_path, config['s3']['bucket'], s3_tfidf_key)

s3_tfidf_path = f"s3://{config['s3']['bucket']}/{s3_tfidf_key}"
print(f"  ✅ Uploaded: {s3_tfidf_path}")

# Cleanup
os.unlink(local_tfidf_path)

# Save metadata
print("\nSaving metadata...")
metadata = {
    'timestamp': datetime.now().isoformat(),
    'date_range': date_range,
    'fixed_version': True,
    'features': {
        'unified_features': 95,
        'base_features': 78,
        'historical_features': 17,
        'tfidf_features': tfidf_pipeline.vocab_size,
        'total_features': config['features']['total_features']
    },
    'parity_validation': parity_result,
    's3_paths': {
        'train': train_path,
        'val': val_path,
        'test': test_path,
        'tfidf_vectorizer': s3_tfidf_path
    },
    'class_distributions': {
        'train': f'{train_ratio:.1f}:1',
        'val': f'{val_ratio:.1f}:1',
        'test': f'{test_ratio:.1f}:1'
    }
}

# Save metadata
with tempfile.NamedTemporaryFile(mode='w', delete=False, suffix='.json') as tmp:
    json.dump(metadata, tmp, indent=2)
    local_metadata_path = tmp.name

metadata_key = f"{config['s3']['prefix']}/metadata/features_{date_range}_fixed.json"
s3_client.upload_file(local_metadata_path, config['s3']['bucket'], metadata_key)
print(f"  ✅ Metadata saved: s3://{config['s3']['bucket']}/{metadata_key}")

# Cleanup
os.unlink(local_metadata_path)

FloatProgress(value=0.0, bar_style='info', description='Progress:', layout=Layout(height='25px', width='50%'),…

Saving TF-IDF vectorizer...
  ? Uploaded: s3://uip-datalake-bucket-prod/sf_trino/trino_query_predictor/models/tfidf_vectorizer_2025-08-01_to_2025-10-01_fixed.pkl

Saving metadata...
  ? Metadata saved: s3://uip-datalake-bucket-prod/sf_trino/trino_query_predictor/metadata/features_2025-08-01_to_2025-10-01_fixed.json

## 17. Summary Report

In [20]:
print("="*70)
print("FEATURE ENGINEERING SUMMARY (FIXED VERSION)")
print("="*70)

print(f"\n✅ KEY FIX APPLIED:")
print(f"  Used unified FeatureExtractor with historical features enabled")
print(f"  Training and inference use identical configuration")
print(f"  AST parser settings consistent")

print(f"\nFeature Breakdown:")
print(f"  Unified features:    95 (78 base + 17 historical)")
print(f"  TF-IDF features:     {tfidf_pipeline.vocab_size}")
print(f"  {'-' * 40}")
print(f"  Total features:      {config['features']['total_features']}")

print(f"\nDataset Sizes:")
print(f"  Train: {train_count:,} queries")
print(f"  Val:   {val_count:,} queries")
print(f"  Test:  {test_count:,} queries")

print(f"\nClass Distributions:")
print(f"  Train: {train_ratio:.1f}:1 (sampled)")
print(f"  Val:   {val_ratio:.1f}:1 (original)")
print(f"  Test:  {test_ratio:.1f}:1 (original)")

print(f"\nParity Validation:")
if parity_result['passed']:
    print(f"  Status: ✅ PASSED")
    print(f"  Mismatch rate: {parity_result['mismatch_rate']:.2f}%")
else:
    print(f"  Status: ❌ FAILED")
    print(f"  Mismatch rate: {parity_result['mismatch_rate']:.2f}%")
    print(f"  Investigation needed for remaining issues")

print(f"\nS3 Outputs (fixed version):")
print(f"  Features: {output_base}/")
print(f"  TF-IDF: {s3_tfidf_path}")
print(f"  Metadata: s3://{config['s3']['bucket']}/{metadata_key}")

print("\n" + "="*70)
print("FEATURE ENGINEERING COMPLETE (FIXED VERSION)")
print("="*70)

print("\nNext Steps:")
if parity_result['passed']:
    print("1. ✅ Proceed to notebook 04 for model training")
    print("2. Use the fixed feature datasets for training")
else:
    print("1. ⚠️  Investigate remaining parity issues")
    print("2. Check AST parser behavior in detail")
    print("3. May need to disable AST features if issues persist")

FloatProgress(value=0.0, bar_style='info', description='Progress:', layout=Layout(height='25px', width='50%'),…

FEATURE ENGINEERING SUMMARY (FIXED VERSION)

? KEY FIX APPLIED:
  Used unified FeatureExtractor with historical features enabled
  Training and inference use identical configuration
  AST parser settings consistent

Feature Breakdown:
  Unified features:    95 (78 base + 17 historical)
  TF-IDF features:     250
  ----------------------------------------
  Total features:      345

Dataset Sizes:
  Train: 8,782,474 queries
  Val:   14,969,526 queries
  Test:  15,099,750 queries

Class Distributions:
  Train: 5.0:1 (sampled)
  Val:   48.2:1 (original)
  Test:  25.0:1 (original)

Parity Validation:
  Status: ? FAILED
  Mismatch rate: 100.00%
  Investigation needed for remaining issues

S3 Outputs (fixed version):
  Features: s3://uip-datalake-bucket-prod/sf_trino/trino_query_predictor/features/2025-08-01_to_2025-10-01_fixed/
  TF-IDF: s3://uip-datalake-bucket-prod/sf_trino/trino_query_predictor/models/tfidf_vectorizer_2025-08-01_to_2025-10-01_fixed.pkl
  Metadata: s3://uip-datalake-bucke